const mongoose = require('mongoose');

const nexttreatSchema = new mongoose.Schema({
zadik:{type:Number},
zadik_des:{type:String},
maamad:{type:Number},
maamad_des:{type:String},
Designation:{type:Number},
Designation_des:{type:String},
birthdate:{type:Date},
unit:{type:Number},
unit_des:{type:String},
hativa:{type:Number},
hativa_des:{type:String},
ugda:{type:Number},
ugda_des:{type:String},
pikud:{type:Number},
pikud_des:{type:String},
meaged_al:{type:String},
meaged_al_des:{type:String},
meaged:{type:String},
meaged_des:{type:String},
mekabete:{type:String},
mekabete_des:{type:String},
makat:{type:Number},
makat_des:{type:String},
policy_category:{type:String},
policy:{type:String},
policy_des:{type:String},
policy_treatment:{type:Number},
policy_treatment_des:{type:String},
plan_number:{type:Number},
call_number:{type:Number},
hierarchy:{type:Number},
frequency:{type:Number},
frq_unit:{type:String},
message_num:{type:Number},
message_treatment:{type:Number},
message_treatment_des:{type:String},
message_date:{type:Date},
work_center:{type:Number},
work_site:{type:Number},
work_center_des:{type:String},
planning_date:{type:Date},
lower_tolerance:{type:Date},
upper_tolerance:{type:Date},
last_treatment_date:{type:Date},
order_number:{type:Number},
type_of_treatment_performed:{type:Number},
type_of_treatment_performed_des:{type:String},
//files
}, {timestamps: true});

const Nexttreat = mongoose.model('Nexttreat', nexttreatSchema);

module.exports = Nexttreat;